{% set version = "2.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rxode2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rxode2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rxode2/rxode2_{{ version }}.tar.gz
  sha256: 3bd872536821635d57007911b3f499aea2c497d6347cf1976a84f73f3b27d264

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
    - '*/Rblas.dll'       # [win]
    - '*/Rlapack.dll'     # [win]
  skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}sed                   # [win]
    - {{ posix }}grep                  # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake              # [not win]
    - {{ posix }}automake-wrapper      # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - libgomp                          # [linux]
    - llvm-openmp                      # [osx]
  host:
    - r-base
    - r-bh
    - r-backports
    - r-checkmate
    - r-cli >=2.0.0
    - r-data.table >=1.12.4
    - r-ggplot2 >=3.4.0
    - r-inline
    - r-lotri >=0.4.0
    - r-magrittr
    - r-memoise
    - r-precisesums >=0.3
    - r-qs >=0.26.3
    - r-rcpp >=0.12.3
    - r-rcpparmadillo >=0.9.300.2.0
    - r-rex
    - r-rxode2et >=2.0.13
    - r-rxode2ll >=2.0.9
    - r-rxode2parse >2.0.19
    - r-rxode2random >2.0.13
    - r-sys
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    #- r-bh
    - r-backports
    - r-checkmate
    - r-cli >=2.0.0
    - r-data.table >=1.12.4
    - r-ggplot2 >=3.4.0
    - r-inline
    - r-lotri >=0.4.0
    - r-magrittr
    - r-memoise
    - r-precisesums >=0.3
    - r-qs >=0.26.3
    - r-rcpp >=0.12.3
    - r-rcpparmadillo >=0.9.300.2.0
    - r-rex
    - r-rxode2et >=2.0.13
    - r-rxode2ll >=2.0.9
    - r-rxode2parse >2.0.19
    - r-rxode2random >2.0.13
    - r-sys

test:
  commands:
    - $R -e "library('rxode2')"           # [not win]
    - "\"%R%\" -e \"library('rxode2')\""  # [win]

about:
  home: https://nlmixr2.github.io/rxode2/
  dev_url: https://github.com/nlmixr2/rxode2/
  license: GPL-3.0-or-later
  summary: 'Facilities for running simulations from ordinary differential equation (''ODE'') models, such as pharmacometrics and other compartmental models.  A compilation manager translates the ODE model into C, compiles it, and dynamically loads the object code into R for improved computational efficiency.  An event table
    object facilitates the specification of complex dosing regimens (optional) and sampling schedules.  NB: The use of this package requires both C and Fortran compilers, for details on their use with R please see Section 6.3, Appendix A, and Appendix D in the "R Administration and Installation" manual. Also the code is
    mostly released under GPL.  The ''VODE'' and ''LSODA'' are in the public domain.  The information is available in the inst/COPYRIGHTS.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
